FROM nginx:alpine

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf
# Copy custom nginx config
COPY ./nginx.conf /etc/nginx/nginx.conf


# Create directories for apps
RUN mkdir -p /usr/share/nginx/html/frontend
RUN mkdir -p /usr/share/nginx/html/backoffice

# Copy frontend build
COPY --from=minodu-frontend:latest /app/build /usr/share/nginx/html/frontend
# Copy backoffice build  
COPY --from=minodu-backoffice:latest /app/dist/minodu-backoffice/browser /usr/share/nginx/html/backoffice

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1

EXPOSE 80 8080