### Build stage Frontend ###
FROM node:18-alpine AS frontend-builder
WORKDIR /app
# Copy package files
COPY apps/minodu-frontend/package*.json ./
# Install dependencies
RUN npm ci
# Copy source code
COPY apps/minodu-frontend/ ./
# Build the app
RUN npm run build
CMD ["echo", "Frontent build completed"]

### Build stage Backoffice ###
FROM node:18-alpine AS backoffice-builder
WORKDIR /app
# Copy package files
COPY apps/minodu-backoffice/package*.json ./
# Install dependencies
RUN npm ci
# Copy source code
COPY apps/minodu-backoffice/ ./
# Build the app
RUN npm run build
CMD ["echo", "Backoffice build completed"]

### Build Stage nginx ###
FROM nginx:alpine
# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf
# Copy custom nginx config
COPY ./nginx.conf /etc/nginx/nginx.conf
# Create directories for apps
RUN mkdir -p /usr/share/nginx/html/frontend
RUN mkdir -p /usr/share/nginx/html/backoffice
# Copy frontend build
COPY --from=frontend-builder /app/build /usr/share/nginx/html/frontend
# Copy backoffice build  
COPY --from=backoffice-builder /app/dist/minodu-backoffice/browser /usr/share/nginx/html/backoffice
# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1
EXPOSE 80 8080