services:
  app:
    build: .
    container_name: minodu-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: minodu-database
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: minodu
      APP_PORT: 3000
      APP_HOST: http://localhost:3000
      APP_FRONT: http://localhost #[http://localhost,http://minodu.chickenkiller.com]
      JWT_SECRET: OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4
    networks:
      - mysql-network
    restart: unless-stopped

networks:
  mysql-network:
    external: true
    name: minodu-network